[tool.poetry]
name = "pybaqus"
version = "0.1.0"
description = ""
authors = ["Cristóbal Tapia Camú <crtapia@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.7"
numpy = "^1.18.2"
scipy = "^1.4.1"
matplotlib = "^3.2.1"
pyvista = "^0.24.1"
vtk = "^8.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
